name: 'Golang build and test'

on:
  pull_request:
    types: [opened, reopened]
  merge_group:
    branches: [develop, main]

jobs:
  call-terraform-security:
    uses: corbencreatives/action-workflows/.github/workflows/golang-build-test.yml@v0.5.4
    permissions:
      contents: read
