name: 'Deploy'

on:
  workflow_run:
    workflows: ['Publish']
#    branches: [develop, main]
    types: [completed]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install helm
#        id: install_helm
        uses: azure/setup-helm@v3
        with:
          # version: '<version>' # default is latest (stable)
          token: ${{ secrets.REGISTRY_TOKEN }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Package helm chart
        run: helm package chart

#      - name: Login to registry
#        run: helm registry login ${{ env.REGISTRY }}/${{ github.repository_owner }} -u ${{ github.repository_owner }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push chart to registry
        run: helm push ./actions-test-0.1.0.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts

      - name: Install kubectl
#        id: install_kubectl
        uses: azure/setup-kubectl@v4.0.0
#        with:
#          version: 'v4.0.0' # default is latest stable

      - name: Create kube config
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Set up the kubeconfig from the secret
      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ./kube_config

      - name: Deploy to k8s
        run: |
          helm upgrade --install actions-test oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/actions-test --version 0.1.0 --kubeconfig ./kube_config --kube-context cicdcluster --namespace cicd --create-namespace --insecure-skip-tls-verify

#      - name: Deploy to k8s
#        # Parameters are pulled directly from the GitHub deployment event so the
#        # configuration for the job here is very minimal.
#        uses: 'deliverybot/helm@v1'
#        with:
#          release: 'nginx'
#          namespace: 'cicd'
#          chart: 'app'
#          version: '${{ github.sha }}'
#          token: '${{ github.token }}'
#        env:
#          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
