name: 'Deploy'

on:
  workflow_run:
    workflows: ['Publish']
#    branches: [develop, main]
    types: [completed]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Package helm chart
        run: helm package chart

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push chart to registry
        run: helm push ./actions-test-0.1.0.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts

      # Log in to Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # Get the kube config for AKS
      - name: Get kube config for AKS
        run: |
          az aks get-credentials --resource-group rg-cicd-apps --name cicdcluster

      - name: Deploy to k8s
        run: |
          helm upgrade --install actions-test oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/actions-test --version latest --namespace cicd --create-namespace --insecure-skip-tls-verify

