name: 'Terraform Destroy Workspace'

on:
  workflow_dispatch:

env:
  TF_WORKSPACE: "actions-test"
  CONFIG_DIRECTORY: "./terraform"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  destroy-workspace:
    runs-on: ubuntu-latest
    name: Destroy Terraform workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform destroy
        uses: dflook/terraform-destroy@v1
        with:
          path: ${{ env.CONFIG_DIRECTORY }}
          workspace: ${{ env.TF_WORKSPACE }}

